name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: peizheg
          template: classic
          base: header, activity, community, repositories, metadata
          base_hireable: yes
          config_timezone: America/Toronto
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: percentage, lines
          plugin_languages_recent_days: 365
          plugin_topics: yes
          plugin_topics_mode: icons
          plugin_languages_ignored: "jupyter notebook, roff, html, css"
